services:
  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    hostname: calculator
    container_name: calculator
    ports:
      - "8000:8000"
    volumes:
      - ./calculator/src/calculator:/app/calculator

  grpc_api:
    build:
      context: .
      dockerfile: grpc_api/Dockerfile
    hostname: grpc_api
    container_name: grpc_api
    ports:
      - "50051:50051"
    volumes:
      - ./grpc_api/src/grpc_api:/app/grpc_api
