services:
  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    hostname: calculator
    container_name: calculator
    ports:
      - "8000:8000"
    volumes:
      - ./calculator:/app/calculator

  add:
    build:
      context: .
      dockerfile: add/Dockerfile
    hostname: add
    container_name: add
    ports:
      - "50051:50051"
    volumes:
      - ./add:/app/add
