services:
  calculator:
    build:
      context: .
      dockerfile: calculator/Dockerfile
    hostname: calculator
    container_name: calculator
    ports:
      - "8000:8000"
    volumes:
      - ./calculator/src/calculator:/app/calculator

  rest_api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
    hostname: rest_api
    container_name: rest_api
    ports:
      - "8100:8000"
    volumes:
      - ./rest_api/src/rest_api:/app/rest_api

  grpc_api:
    build:
      context: .
      dockerfile: grpc_api/Dockerfile
    hostname: grpc_api
    container_name: grpc_api
    ports:
      - "50051:50051"
    volumes:
      - ./grpc_api/src/grpc_api:/app/grpc_api
