"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import typing

import google.protobuf.descriptor
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FakeTimeSeriesRequest(google.protobuf.message.Message):
    """Request to fetch a time series of a specific length"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LENGTH_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    length: builtins.int
    """The desired length of the time series"""
    source: builtins.str
    """Optional source identifier"""
    filter: builtins.str
    """Optional filter for data"""
    def __init__(
        self,
        *,
        length: builtins.int = ...,
        source: builtins.str = ...,
        filter: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "length", b"length", "source", b"source"]) -> None: ...

global___FakeTimeSeriesRequest = FakeTimeSeriesRequest

@typing.final
class FakeTimeSeriesResponse(google.protobuf.message.Message):
    """Response containing the serialized time series"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIALIZED_SERIES_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    serialized_series: builtins.bytes
    """Serialized time series data (e.g., in Arrow format)"""
    metadata: builtins.str
    """Metadata about the time series"""
    def __init__(
        self,
        *,
        serialized_series: builtins.bytes = ...,
        metadata: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "serialized_series", b"serialized_series"]) -> None: ...

global___FakeTimeSeriesResponse = FakeTimeSeriesResponse
