"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TimeSeriesRequest(google.protobuf.message.Message):
    """Request to fetch a time series of a specific length"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int
    """The desired length of the time series"""
    def __init__(
        self,
        *,
        length: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["length", b"length"]) -> None: ...

global___TimeSeriesRequest = TimeSeriesRequest

@typing.final
class TimeSeriesResponse(google.protobuf.message.Message):
    """Response containing the serialized time series"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIALIZED_SERIES_FIELD_NUMBER: builtins.int
    serialized_series: builtins.bytes
    """Serialized time series data (in Arrow format)"""
    def __init__(
        self,
        *,
        serialized_series: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["serialized_series", b"serialized_series"]) -> None: ...

global___TimeSeriesResponse = TimeSeriesResponse
