# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: time_series.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'time_series.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11time_series.proto\x12\x0btime_series\"#\n\x11TimeSeriesRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\"/\n\x12TimeSeriesResponse\x12\x19\n\x11serialized_series\x18\x01 \x01(\x0c\x32j\n\x11TimeSeriesService\x12U\n\x12GenerateTimeSeries\x12\x1e.time_series.TimeSeriesRequest\x1a\x1f.time_series.TimeSeriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_series_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESERIESREQUEST']._serialized_start=34
  _globals['_TIMESERIESREQUEST']._serialized_end=69
  _globals['_TIMESERIESRESPONSE']._serialized_start=71
  _globals['_TIMESERIESRESPONSE']._serialized_end=118
  _globals['_TIMESERIESSERVICE']._serialized_start=120
  _globals['_TIMESERIESSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
